document.addEventListener('DOMContentLoaded',()=>{
 const D=window.DIADE_DATA,page=document.body.dataset.page;
 const plan=()=>localStorage.getItem('medudemyPlan')||'free';
 const applyPlan=()=>{document.body.classList.toggle('proPlan',plan()==='pro');document.querySelectorAll('[data-plan]').forEach(x=>x.textContent=plan()==='pro'?'Pro Preview':'Free')};
 const toast=m=>{const t=document.querySelector('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window._dt);window._dt=setTimeout(()=>t.classList.remove('show'),2800)};
 const saved=()=>{try{return JSON.parse(localStorage.getItem('medudemySaved')||'[]')}catch{return[]}};
 const toggleSaved=id=>{let a=saved();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('medudemySaved',JSON.stringify(a));return a.includes(id)};
 const qstate=()=>{try{return JSON.parse(localStorage.getItem('medudemyQ')||'{}')}catch{return{}}};
 document.querySelectorAll('[data-year]').forEach(x=>x.textContent=new Date().getFullYear());
 document.querySelector('.menu')?.addEventListener('click',e=>{const n=document.querySelector('header nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});
 document.querySelector('#planChip')?.addEventListener('click',()=>location.href='pricing.html');applyPlan();
 document.querySelectorAll('a[href^="http"]').forEach(a=>a.rel='noopener');

 if(page==='home'){
  const c=document.querySelector('#homeReviewers');D.reviews.slice(0,6).forEach(r=>c.insertAdjacentHTML('beforeend',`<a class="reviewCard mini" href="${r.url||'reviewers.html#'+r.id}"><div class="rIcon">${r.icon}</div><small>${r.level} • ${r.subject}</small><h3>${r.title}</h3><p>${r.description}</p></a>`));
 }

 if(page==='dashboard'){
  const render=()=>{const s=qstate(),vals=Object.values(s),correct=vals.filter(x=>x.correct).length;document.querySelector('#mAnswered').textContent=vals.length;document.querySelector('#mAccuracy').textContent=vals.length?Math.round(correct/vals.length*100)+'%':'—';document.querySelector('#mSaved').textContent=saved().length;document.querySelector('#mAi').textContent=localStorage.getItem('medudemyAiUsage')||0;document.querySelector('#planCopy').textContent=plan()==='pro'?'All prototype reviewers, questions, and AI messages are unlocked.':'Sample access to reviewers, questions, and AI prompts.'};
  const renderSubjects=()=>{const c=document.querySelector('#subjectProgress'),started=JSON.parse(localStorage.getItem('medudemyStarted')||'[]');c.innerHTML=D.ple.map(s=>`<button class="${started.includes(s.slug)?'started':''}" data-sub="${s.slug}"><small>${s.number}</small><b>${s.title}</b></button>`).join('');c.querySelectorAll('button').forEach(b=>b.onclick=()=>{let a=JSON.parse(localStorage.getItem('medudemyStarted')||'[]');a=a.includes(b.dataset.sub)?a.filter(x=>x!==b.dataset.sub):[...a,b.dataset.sub];localStorage.setItem('medudemyStarted',JSON.stringify(a));renderSubjects()})};
  const renderSaved=()=>{const c=document.querySelector('#savedList'),arr=D.reviews.filter(r=>saved().includes(r.id));c.innerHTML=arr.length?arr.map(r=>`<a href="${r.url||'reviewers.html#'+r.id}"><span>${r.icon}</span><div><b>${r.title}</b><small>${r.subject}</small></div></a>`).join(''):'<p class="muted">No saved reviewers yet.</p>'};
  document.querySelector('#resetSubjects').onclick=()=>{localStorage.removeItem('medudemyStarted');renderSubjects();toast('Subject progress reset.')};render();renderSubjects();renderSaved();
 }

 if(page==='nmat'){
  document.querySelector('#makeNmat').onclick=()=>{const n=+document.querySelector('#nmatWeeks').value,phase=(i)=>i===1?'Baseline diagnostic, schedule, and error-log setup':i/n<=.35?'Foundation review plus short daily Part 1 drills':i/n<=.68?'Mixed practice, speed work, and weak-topic repair':i/n<=.88?'Timed sections, simulations, and error analysis':'Targeted refreshers, logistics, sleep, and taper';document.querySelector('#nmatResult').innerHTML=`<h3>${n}-Week NMAT Starter Roadmap</h3>`+Array.from({length:n},(_,i)=>`<div><b>Week ${i+1}</b><span>${phase(i+1)}</span></div>`).join('')};
 }

 if(page==='ple'){
  const grid=document.querySelector('#pleGrid'),dlg=document.querySelector('#subjectDialog');grid.innerHTML=D.ple.map(s=>`<button class="pleCard" data-slug="${s.slug}"><div><span>${s.icon}</span><small>SUBJECT ${s.number}</small></div><h3>${s.title}</h3><p>${s.summary}</p><b>${s.topics.length} topic areas →</b></button>`).join('');
  let current=null;const setButton=()=>{const a=JSON.parse(localStorage.getItem('medudemyStarted')||'[]');document.querySelector('#dlgStarted').textContent=a.includes(current.slug)?'✓ Started — undo':'Mark as started'};
  grid.querySelectorAll('button').forEach(b=>b.onclick=()=>{current=D.ple.find(x=>x.slug===b.dataset.slug);document.querySelector('#dlgKicker').textContent=`PLE SUBJECT ${current.number}`;document.querySelector('#dlgIcon').textContent=current.icon;document.querySelector('#dlgTitle').textContent=current.title;document.querySelector('#dlgSummary').textContent=current.summary;document.querySelector('#dlgTopics').innerHTML=current.topics.map(x=>`<label><input type="checkbox"> ${x}</label>`).join('');document.querySelector('#dlgStarter').textContent=current.starter;setButton();dlg.showModal()});
  dlg.querySelector('.close').onclick=()=>dlg.close();dlg.addEventListener('click',e=>{const r=dlg.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dlg.close()});document.querySelector('#dlgStarted').onclick=()=>{let a=JSON.parse(localStorage.getItem('medudemyStarted')||'[]');a=a.includes(current.slug)?a.filter(x=>x!==current.slug):[...a,current.slug];localStorage.setItem('medudemyStarted',JSON.stringify(a));setButton()};
 }

 if(page==='reviewers'){
  const grid=document.querySelector('#reviewGrid'),search=document.querySelector('#reviewSearch'),count=document.querySelector('#reviewCount'),dlg=document.querySelector('#reviewDialog');let filter='all',current=null;
  const open=id=>{const r=D.reviews.find(x=>x.id===id);if(!r)return;if(r.url){location.href=r.url;return}if(r.level==='Pro'&&plan()!=='pro'){location.href='pricing.html';return}current=r;document.querySelector('#readerIcon').textContent=r.icon;document.querySelector('#readerMeta').textContent=`${r.level} • ${r.subject} • ${r.category}`;document.querySelector('#readerTitle').textContent=r.title;document.querySelector('#readerDesc').textContent=r.description;document.querySelector('#readerObjectives').innerHTML=r.objectives.map(x=>`<li>${x}</li>`).join('');document.querySelector('#readerSections').innerHTML=r.sections.map(x=>`<article><h4>${x[0]}</h4><p>${x[1]}</p></article>`).join('');document.querySelector('#readerPrompts').innerHTML=r.prompts.map(x=>`<span>${x}</span>`).join('');document.querySelector('#readerRefs').innerHTML=r.references.map(x=>`<li>${x}</li>`).join('');document.querySelector('#saveReview').textContent=saved().includes(r.id)?'★ Saved reviewer':'☆ Save reviewer';dlg.showModal()};
  const render=()=>{const term=search.value.toLowerCase(),items=D.reviews.filter(r=>(filter==='all'||r.level===filter||r.category===filter)&&(`${r.title} ${r.subject} ${r.category} ${r.description}`.toLowerCase().includes(term)));count.textContent=`${items.length} reviewer${items.length===1?'':'s'}`;grid.innerHTML=items.map(r=>{const lock=r.level==='Pro'&&plan()!=='pro';return`<article class="reviewCard ${r.level.toLowerCase()}"><div class="rIcon">${r.icon}</div><small>${r.level} • ${r.subject}</small><h3>${r.title}</h3><p>${r.description}</p><div class="cardActions"><button data-open="${r.id}">Open</button><button data-save="${r.id}">${saved().includes(r.id)?'★':'☆'}</button></div>${lock?'<div class="locked"><span>🔒</span><b>Pro preview</b><a href="pricing.html">Unlock →</a></div>':''}</article>`}).join('');grid.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open));grid.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const x=toggleSaved(b.dataset.save);b.textContent=x?'★':'☆';toast(x?'Reviewer saved.':'Reviewer removed.')})};
  search.oninput=render;document.querySelectorAll('[data-rfilter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-rfilter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.rfilter;render()});dlg.querySelector('.close').onclick=()=>dlg.close();document.querySelector('#saveReview').onclick=()=>{const x=toggleSaved(current.id);document.querySelector('#saveReview').textContent=x?'★ Saved reviewer':'☆ Save reviewer';toast(x?'Reviewer saved.':'Reviewer removed.')};window.addEventListener('hashchange',()=>open(location.hash.slice(1)));render();if(location.hash)open(location.hash.slice(1));
 }

 if(page==='qbank'){
  const list=document.querySelector('#qList'),filter=document.querySelector('#qFilter');let state=qstate();[...new Set(D.qbank.map(q=>q.subject))].forEach(s=>filter.insertAdjacentHTML('beforeend',`<option>${s}</option>`));const requested=new URLSearchParams(location.search).get('subject');if(requested&&[...filter.options].some(o=>o.value===requested))filter.value=requested;
  const score=()=>{const v=Object.values(state),c=v.filter(x=>x.correct).length;document.querySelector('#scoreValue').textContent=`${c} / ${v.length}`;document.querySelector('#scoreBar').style.width=v.length?c/v.length*100+'%':'0%'};
  const render=()=>{const items=D.qbank.filter(q=>filter.value==='all'||q.subject===filter.value),p=plan();document.querySelector('#qAvailable').textContent=items.filter(q=>q.level==='Free'||p==='pro').length;list.innerHTML=items.map((q,i)=>{if(q.level==='Pro'&&p!=='pro')return`<article class="qcard qlock"><span>🔒</span><h3>${q.subject} Pro question</h3><a class="btn outline" href="pricing.html">Unlock preview</a></article>`;return`<article class="qcard" data-id="${q.id}"><small>${q.subject} • ${q.level}</small><h3>${q.stem}</h3><div class="options">${q.options.map((o,j)=>`<label><input type="radio" name="q${q.id}" value="${j}"> ${o}</label>`).join('')}</div><button class="check">Check answer</button><div class="explain"></div></article>`}).join('');list.querySelectorAll('.qcard[data-id]').forEach(card=>{const q=D.qbank.find(x=>x.id==card.dataset.id),old=state[q.id];const show=(sel,persist)=>{const ok=+sel===q.answer,e=card.querySelector('.explain');e.className='explain show '+(ok?'ok':'bad');e.innerHTML=`<b>${ok?'Correct.':'Best answer: '+q.options[q.answer]}</b><p>${q.explanation}</p><small>${q.takeaway}</small>`;card.querySelectorAll('input').forEach(x=>x.disabled=true);card.querySelector('.check').disabled=true;if(persist){state[q.id]={selected:+sel,correct:ok};localStorage.setItem('medudemyQ',JSON.stringify(state))}score()};if(old){const x=card.querySelector(`input[value="${old.selected}"]`);if(x)x.checked=true;show(old.selected,false)}card.querySelector('.check').onclick=()=>{const x=card.querySelector('input:checked');if(!x){toast('Choose an answer first.');return}show(x.value,true)}});score()};
  filter.onchange=render;document.querySelector('#resetQ').onclick=()=>{state={};localStorage.setItem('medudemyQ','{}');render();toast('QBank reset.')};render();
 }

 if(page==='ai'){
  const form=document.querySelector('#chatForm'),input=document.querySelector('#chatInput'),msgs=document.querySelector('#messages'),file=document.querySelector('#aiFile'),info=document.querySelector('#fileInfo'),usageEl=document.querySelector('#aiUsage');let doc='',filename='',usage=+(localStorage.getItem('medudemyAiUsage')||0);
  const update=()=>usageEl.textContent=plan()==='pro'?`Pro preview: ${usage} messages used`:`Free demo: ${usage} / 5 messages used`;
  const add=(role,html)=>{msgs.insertAdjacentHTML('beforeend',`<div class="msg ${role}"><span>${role==='user'?'Y':'D'}</span><div>${html}</div></div>`);msgs.scrollTop=msgs.scrollHeight};
  const find=q=>{if(!doc)return null;const keys=q.toLowerCase().split(/\W+/).filter(x=>x.length>3),s=doc.split(/(?<=[.!?])\s+|\n+/).filter(x=>x.length>25).map(x=>({x,score:keys.reduce((n,k)=>n+(x.toLowerCase().includes(k)?1:0),0)})).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,3);return s.length?s.map(x=>x.x.trim()).join(' … '):null};
  const reply=q=>{const hit=find(q);if(hit)return`<b>Found in ${filename}:</b><p>${hit.slice(0,900)}</p><small>Local keyword match only.</small>`;const l=q.toLowerCase();if(l.includes('cardiac'))return'<b>Cardiac cycle:</b><p>Ventricular filling → isovolumetric contraction → ejection → isovolumetric relaxation. Valve motion follows pressure gradients.</p>';if(l.includes('acid')||l.includes('base'))return'<b>Acid–base sequence:</b><p>pH direction → primary process → expected compensation → mixed disorder → clinical context.</p>';if(l.includes('drug')||l.includes('pharmac'))return'<b>Drug-class map:</b><p>Target → mechanism → effect → indication → adverse effects → contraindications → monitoring.</p>';if(l.includes('ple')||l.includes('board'))return'<b>PLE cycle:</b><p>Map → diagnose → review → practice → revisit.</p>';return'<b>Demo limitation</b><p>No real language model is connected. Ask about built-in frameworks or search an uploaded TXT/Markdown file.</p>'};
  const submit=q=>{if(plan()!=='pro'&&usage>=5){add('bot','<b>Free demo limit reached.</b><p>Activate Pro preview to continue.</p>');return}add('user',`<p>${q.replace(/[<>]/g,'')}</p>`);usage++;localStorage.setItem('medudemyAiUsage',usage);update();setTimeout(()=>add('bot',reply(q)),250)};
  form.onsubmit=e=>{e.preventDefault();const q=input.value.trim();if(q){input.value='';submit(q)}};document.querySelectorAll('.suggest button').forEach(b=>b.onclick=()=>submit(b.textContent));file.onchange=async()=>{const f=file.files[0];if(!f)return;filename=f.name;const ext=f.name.split('.').pop().toLowerCase();if(['txt','md'].includes(ext)){doc=(await f.text()).slice(0,100000);info.innerHTML=`<div class="filechip"><b>${f.name}</b><small>${Math.round(f.size/1024)} KB • readable locally</small></div>`;add('bot',`<b>${f.name} is ready.</b><p>Ask me to find a concept inside it.</p>`)}else{doc='';info.innerHTML=`<div class="filechip"><b>${f.name}</b><small>${Math.round(f.size/1024)} KB • backend required</small></div>`;add('bot',`<b>I cannot read ${ext.toUpperCase()} locally.</b><p>A production backend must securely parse this file.</p>`)}};document.querySelector('#clearChat').onclick=()=>msgs.innerHTML='<div class="msg bot"><span>D</span><div><b>Chat cleared.</b><p>Your local file remains selected until refresh.</p></div></div>';update();
 }

 if(page==='pricing'){
  const refresh=()=>document.querySelectorAll('[data-setplan]').forEach(b=>b.textContent=b.dataset.setplan===plan()?'✓ Active preview':b.dataset.setplan==='pro'?'Activate Pro preview':'Use Free preview');document.querySelectorAll('[data-setplan]').forEach(b=>b.onclick=()=>{localStorage.setItem('medudemyPlan',b.dataset.setplan);applyPlan();refresh();toast(b.dataset.setplan==='pro'?'Pro preview activated locally.':'Free preview activated.')});refresh();
 }

 if(page==='reviewers'&&location.hash){}
 if(document.querySelector('#resourceDirectory')){document.querySelector('#resourceDirectory').innerHTML=D.resources.map(g=>`<section class="resourceGroup"><span class="eyebrow">${g.group}</span><h2>${g.group}</h2><div class="resourceGrid">${g.items.map(x=>`<a href="${x[2]}" target="_blank"><h3>${x[0]}</h3><p>${x[1]}</p><b>Open source ↗</b></a>`).join('')}</div></section>`).join('')}
});
