document.addEventListener("DOMContentLoaded",()=>{
const questions=[
{topic:"Physiology",stem:"A decrease in renal perfusion most directly stimulates juxtaglomerular cells to release which substance?",options:["Aldosterone","Renin","Antidiuretic hormone","Atrial natriuretic peptide"],answer:1,explanation:"Juxtaglomerular cells release renin when renal perfusion pressure falls. Renin initiates the renin–angiotensin–aldosterone cascade.",takeaway:"Decreased renal perfusion, reduced distal sodium delivery, and sympathetic β1 stimulation can promote renin release."},
{topic:"Anatomy",stem:"Which chamber receives oxygenated blood directly from the pulmonary veins?",options:["Right atrium","Right ventricle","Left atrium","Left ventricle"],answer:2,explanation:"Pulmonary veins return oxygenated blood from the lungs to the left atrium.",takeaway:"Venae cavae → right atrium; pulmonary veins → left atrium."},
{topic:"Physiology",stem:"Which pulmonary cell type primarily produces surfactant?",options:["Type I pneumocyte","Type II pneumocyte","Alveolar macrophage","Ciliated epithelial cell"],answer:1,explanation:"Type II pneumocytes synthesize and secrete surfactant, reducing alveolar surface tension.",takeaway:"Type I supports gas exchange; Type II produces surfactant and can proliferate after injury."},
{topic:"Pharmacology",stem:"Beta-lactam antibiotics primarily inhibit which bacterial process?",options:["Protein synthesis","DNA replication","Cell-wall synthesis","Folate synthesis"],answer:2,explanation:"Beta-lactams bind penicillin-binding proteins and interfere with peptidoglycan cross-linking.",takeaway:"They act on susceptible bacteria actively building cell wall."},
{topic:"Microbiology",stem:"Which structure allows many bacteria to transfer genetic material directly during conjugation?",options:["Capsule","Pilus","Endospore","Flagellum"],answer:1,explanation:"A conjugative or sex pilus helps establish contact for plasmid transfer.",takeaway:"Conjugation is horizontal gene transfer and may spread antimicrobial-resistance genes."},
{topic:"Pathology",stem:"Which term describes a reversible replacement of one mature cell type by another mature cell type better able to tolerate stress?",options:["Dysplasia","Metaplasia","Anaplasia","Hyperplasia"],answer:1,explanation:"Metaplasia is an adaptive, potentially reversible substitution of one differentiated cell type for another.",takeaway:"Persistent stress can make metaplastic tissue vulnerable to dysplastic change."}
];
const list=document.querySelector("#question-list"),filter=document.querySelector("#topic-filter"),score=document.querySelector("#score-value"),bar=document.querySelector("#score-bar"),reset=document.querySelector("#reset-qbank"),state=new Map();
function update(){const a=[...state.values()],c=a.filter(x=>x.correct).length;score.textContent=`${c} / ${a.length}`;bar.style.width=a.length?`${c/a.length*100}%`:"0%"}
function explain(card,index,selected,save=true){const q=questions[index],ok=+selected===q.answer,box=card.querySelector(".explanation");box.className=`explanation show ${ok?"correct":"incorrect"}`;box.innerHTML=`<b>${ok?"Correct.":`Not quite. The best answer is ${q.options[q.answer]}.`}</b><p>${q.explanation}</p><small>${q.takeaway}</small>`;card.querySelectorAll("input").forEach(i=>i.disabled=true);card.querySelector(".check-answer").disabled=true;if(save)state.set(index,{selected:+selected,correct:ok});update()}
function render(){const topic=filter.value,visible=questions.map((q,index)=>({q,index})).filter(x=>topic==="all"||x.q.topic===topic);list.innerHTML=visible.map(({q,index},j)=>`<article class="question-card" data-index="${index}"><div class="question-meta"><span>${q.topic}</span><span>Question ${j+1} of ${visible.length}</span></div><h3>${q.stem}</h3><div class="answer-options">${q.options.map((o,k)=>`<label><input type="radio" name="q-${index}" value="${k}"><span>${o}</span></label>`).join("")}</div><button class="check-answer">Check answer</button><div class="explanation"></div></article>`).join("");visible.forEach(({index})=>{const s=state.get(index),card=list.querySelector(`[data-index="${index}"]`);if(s){card.querySelector(`input[value="${s.selected}"]`).checked=true;explain(card,index,s.selected,false)}});list.querySelectorAll(".question-card").forEach(card=>card.querySelector(".check-answer").addEventListener("click",()=>{const s=card.querySelector("input:checked"),box=card.querySelector(".explanation");if(!s){box.className="explanation show incorrect";box.innerHTML="<b>Choose an answer first.</b><p>Commit to one option before revealing the explanation.</p>";return}explain(card,+card.dataset.index,s.value)}));update()}
filter.addEventListener("change",render);reset.addEventListener("click",()=>{state.clear();render()});render();
});
